export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const SET_PLAYER_TOKEN = 'SET_PLAYER_TOKEN';
export const SET_PLAYER_EMAIL = 'SET_PLAYER_EMAIL';
export const SET_QUESTIONS = 'SET_QUESTIONS';
